--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/supercrafter333/PlotRate
build-by-default: true
branches:
- master
- PM4
projects:
  PlotRate:
    icon: "icon.png"
    path: ""
...
